<script setup lang="ts">
import { onMounted, ref, watch, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, products } from '../api'
import { useAuthStore } from '../stores/auth'
import type { Page, Batch, Product } from '../types'
const auth=useAuthStore(), canControl=computed(()=>auth.user?.role!=='CLERK')
const rows=ref<Page<Batch>>(),catalog=ref<Product[]>([]), productId=ref<number>(),index=ref(0),loading=ref(false),selected=ref<Batch>(),history=ref<any[]>([]),controls=ref<any[]>([]),open=ref(false)
async function load(){loading.value=true;try{rows.value=(await api.get('/batches',{params:{productId:productId.value,page:index.value,size:20}})).data}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not load batches')}finally{loading.value=false}}
onMounted(async()=>{await load();catalog.value=(await products({size:100})).items});watch(productId,()=>{index.value=0;load()});watch(index,load)
async function inspect(b:Batch){selected.value=b;open.value=true;try{history.value=(await api.get(`/batches/${b.id}/history`)).data;controls.value=(await api.get(`/batches/${b.id}/controls`)).data}catch{ElMessage.error('Could not load batch history')}}
async function control(b:Batch){try{const {value}=await ElMessageBox.prompt('Reason',b.quarantined?'Release batch':'Quarantine batch',{inputValidator:v=>!!v?.trim()||'A reason is required',inputPattern:/^.{1,300}$/,inputErrorMessage:'Use 1–300 characters'});await api.post(`/batches/${b.id}/control`,{quarantined:!b.quarantined,reason:value});await load();ElMessage.success('Batch status updated')}catch(e:any){if(e.response)ElMessage.error(e.response.data?.message||'Could not update batch')}}
</script>
<template><section class="view table-view" v-loading="loading"><div class="page-heading"><h1>Batch inventory</h1><el-button @click="load">Refresh</el-button></div><div class="surface-card table-surface"><div class="table-toolbar feature-toolbar"><el-select v-model="productId" clearable filterable placeholder="All products" aria-label="Product filter"><el-option v-for="p in catalog" :key="p.id" :label="p.name" :value="p.id"/></el-select><span>{{ rows?.totalElements||0 }} batches</span></div><el-table :data="rows?.items||[]" stripe><el-table-column prop="productName" label="PRODUCT" min-width="200"/><el-table-column prop="batchNumber" label="BATCH" min-width="180"/><el-table-column prop="receivedDate" label="RECEIVED" width="130"/><el-table-column prop="expiryDate" label="EXPIRY" width="130"/><el-table-column prop="quantity" label="PHYSICAL" width="100"/><el-table-column label="STATUS" width="150"><template #default="{row}"><el-tag :type="row.status==='EXPIRED'?'danger':row.quarantined?'warning':'success'">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="ACTIONS" width="220"><template #default="{row}"><el-button @click="inspect(row)">History</el-button><el-button v-if="canControl&&row.quantity>0" @click="control(row)">{{ row.quarantined?'Release':'Quarantine' }}</el-button></template></el-table-column></el-table><div class="table-pagination"><span>{{ rows?.totalElements||0 }} batches</span><el-pagination :current-page="index+1" @current-change="index=$event-1" :page-size="20" :total="rows?.totalElements||0" layout="prev, pager, next"/></div></div><el-dialog v-model="open" :title="selected?.batchNumber" width="720px"><h3>Stock allocations</h3><el-table :data="history"><el-table-column prop="type" label="ACTIVITY"/><el-table-column prop="delta" label="CHANGE"/><el-table-column prop="actor" label="ACTOR"/><el-table-column prop="reason" label="REASON"/></el-table><h3>Quarantine history</h3><el-table :data="controls"><el-table-column label="ACTION"><template #default="{row}">{{ row.quarantined?'Quarantined':'Released' }}</template></el-table-column><el-table-column prop="reason" label="REASON"/><el-table-column prop="actor" label="ACTOR"/></el-table></el-dialog></section></template>
