<script setup lang="ts">
import { computed, onMounted, ref, reactive, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, products, suppliers } from '../api'
import { useAuthStore } from '../stores/auth'
import type { Product, Supplier, Page } from '../types'
const auth=useAuthStore(),route=useRoute(),manager=computed(()=>auth.user?.role!=='CLERK'),receiver=computed(()=>auth.user?.role!=='MANAGER')
const orders=ref<Page<any>>(),suggestions=ref<any[]>([]),catalog=ref<Product[]>([]),vendors=ref<Supplier[]>([]),index=ref(0),loading=ref(false),saving=ref(false)
const draftOpen=ref(false),detailOpen=ref(false),receiveOpen=ref(false),selected=ref<any>(),history=ref<any[]>([]),receipts=ref<any[]>([]),editId=ref<number>()
const form=reactive({supplierId:undefined as number|undefined,reason:'',warningId:undefined as number|undefined,lines:[{productId:undefined as number|undefined,quantity:1}]})
const receipt=reactive({lineId:undefined as number|undefined,quantity:1,batchNumber:'',productionDate:null as string|null,expiryDate:null as string|null,idempotencyKey:''})
async function load(){loading.value=true;try{orders.value=(await api.get('/purchases',{params:{page:index.value,size:20}})).data;suggestions.value=(await api.get('/replenishment')).data;catalog.value=(await products({size:100})).items;vendors.value=await suppliers()}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not load purchasing')}finally{loading.value=false}}
onMounted(async()=>{await load();if(route.query.productId){const s=suggestions.value.find(s=>s.productId===Number(route.query.productId));if(s)draft(s)}});watch(index,load)
function draft(s?:any){editId.value=undefined;Object.assign(form,{supplierId:s?.supplierId,reason:s?'Stock replenishment':'',warningId:route.query.warningId?Number(route.query.warningId):undefined,lines:[{productId:s?.productId,quantity:s?.suggested||1}]});draftOpen.value=true}
function edit(o:any){editId.value=o.id;Object.assign(form,{supplierId:vendors.value.find(s=>s.name===o.supplier)?.id,reason:o.reason,warningId:o.warningId,lines:o.lines.map((l:any)=>({productId:l.productId,quantity:l.quantity}))});draftOpen.value=true}
async function save(){if(!form.supplierId||!form.reason.trim()||form.lines.some(l=>!l.productId))return ElMessage.warning('Select a supplier, products and reason');saving.value=true;try{if(editId.value)await api.put(`/purchases/${editId.value}`,form);else await api.post('/purchases',form);draftOpen.value=false;await load();ElMessage.success('Draft saved')}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not save draft')}finally{saving.value=false}}
async function inspect(o:any){detailOpen.value=true;try{selected.value=(await api.get(`/purchases/${o.id}`)).data;history.value=(await api.get(`/purchases/${o.id}/history`)).data;receipts.value=(await api.get(`/purchases/${o.id}/receipts`)).data}catch{ElMessage.error('Could not load purchase')}}
async function act(action:string){if(!selected.value)return;try{const {value}=await ElMessageBox.prompt('Reason',action,{inputValidator:v=>!!v?.trim()||'Reason is required'});saving.value=true;await api.post(`/purchases/${selected.value.id}/actions`,{action,note:value});await inspect(selected.value);await load()}catch(e:any){if(e.response)ElMessage.error(e.response.data?.message||'Could not update purchase')}finally{saving.value=false}}
function startReceipt(l:any){Object.assign(receipt,{lineId:l.id,quantity:l.remaining,batchNumber:'',productionDate:null,expiryDate:null,idempotencyKey:crypto.randomUUID()});receiveOpen.value=true}
async function receive(){saving.value=true;try{await api.post(`/purchases/${selected.value.id}/receipts`,{...receipt,batchNumber:receipt.batchNumber||null});receiveOpen.value=false;await inspect(selected.value);await load();ElMessage.success('Receipt recorded')}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not receive stock')}finally{saving.value=false}}
async function target(s:any){try{const {value}=await ElMessageBox.prompt('Target stock',s.productName,{inputValue:String(s.target),inputValidator:v=>Number.isInteger(Number(v))&&Number(v)>s.trigger||'Target must exceed trigger'});await api.patch(`/products/${s.productId}/target`,{targetStock:Number(value)});await load()}catch(e:any){if(e.response)ElMessage.error(e.response.data?.message||'Could not update target')}}
</script>
<template><section class="view table-view" v-loading="loading"><div class="page-heading"><h1>Purchasing</h1><el-button type="primary" @click="draft()">New purchase</el-button></div>
 <article class="surface-card table-surface replenishment-surface"><div class="table-toolbar"><h2>Replenishment suggestions</h2></div><el-table :data="suggestions" class="replenishment-table"><el-table-column prop="productName" label="PRODUCT" min-width="220"/><el-table-column prop="sellable" label="SELLABLE" width="120"/><el-table-column prop="pending" label="PENDING" width="120"/><el-table-column prop="position" label="POSITION" width="120"/><el-table-column prop="trigger" label="TRIGGER" width="110"/><el-table-column prop="target" label="TARGET" width="110"/><el-table-column prop="suggested" label="SUGGESTED" width="130"/><el-table-column prop="supplier" label="SUPPLIER" min-width="180"/><el-table-column label="ACTIONS" width="245"><template #default="{row}"><span class="purchase-row-actions"><el-button @click="draft(row)">Create draft</el-button><el-button v-if="manager" @click="target(row)">Target</el-button></span></template></el-table-column><template #empty>No replenishment required</template></el-table></article>
 <article class="surface-card table-surface" style="margin-top:24px"><div class="table-toolbar"><h2>Purchase orders</h2><el-button @click="load">Refresh</el-button></div><el-table :data="orders?.items||[]" stripe><el-table-column prop="id" label="ORDER" width="90"/><el-table-column prop="supplier" label="SUPPLIER" min-width="180"/><el-table-column prop="state" label="STATUS" width="150"/><el-table-column prop="createdBy" label="CREATED BY" min-width="160"/><el-table-column prop="reason" label="REASON" min-width="180"/><el-table-column width="120"><template #default="{row}"><el-button @click="inspect(row)">Details</el-button></template></el-table-column></el-table><div class="table-pagination"><span>{{ orders?.totalElements||0 }} orders</span><el-pagination :current-page="index+1" @current-change="index=$event-1" :page-size="20" :total="orders?.totalElements||0" layout="prev, pager, next"/></div></article>
 <el-dialog v-model="draftOpen" :title="editId?'Edit purchase':'Purchase draft'" width="720px"><el-form label-position="top"><el-form-item label="Supplier"><el-select v-model="form.supplierId" filterable><el-option v-for="s in vendors" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><div v-for="(l,i) in form.lines" :key="i" class="feature-grid"><el-form-item label="Product"><el-select v-model="l.productId" filterable><el-option v-for="p in catalog" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="Quantity"><el-input-number v-model="l.quantity" :min="1" :max="1000000000"/></el-form-item><el-button v-if="form.lines.length>1" @click="form.lines.splice(i,1)">Remove</el-button></div><el-button @click="form.lines.push({productId:undefined,quantity:1})">Add product</el-button><el-form-item label="Reason"><el-input v-model="form.reason" type="textarea" maxlength="300"/></el-form-item></el-form><template #footer><el-button @click="draftOpen=false">Cancel</el-button><el-button type="primary" :loading="saving" @click="save">Save draft</el-button></template></el-dialog>
 <el-dialog v-model="detailOpen" :title="`Purchase #${selected?.id||''}`" width="860px"><template v-if="selected"><div class="feature-facts"><span>{{ selected.supplier }}</span><b>{{ selected.state }}</b><span v-if="selected.warningId">Warning #{{ selected.warningId }}</span><span>{{ selected.reviewNote }}</span></div><el-table :data="selected.lines"><el-table-column prop="productName" label="PRODUCT"/><el-table-column prop="quantity" label="APPROVED / REQUESTED"/><el-table-column prop="received" label="RECEIVED"/><el-table-column prop="remaining" label="REMAINING"/><el-table-column v-if="receiver&&['APPROVED','PARTIAL'].includes(selected.state)"><template #default="{row}"><el-button v-if="row.remaining>0" @click="startReceipt(row)">Receive</el-button></template></el-table-column></el-table><div class="feature-actions"><el-button v-if="['DRAFT','REJECTED'].includes(selected.state)" @click="edit(selected)">Edit</el-button><el-button v-if="['DRAFT','REJECTED'].includes(selected.state)" :disabled="saving" @click="act('SUBMIT')">Submit</el-button><template v-if="manager&&selected.state==='SUBMITTED'"><el-button type="primary" :disabled="saving" @click="act('APPROVE')">Approve</el-button><el-button :disabled="saving" @click="act('REJECT')">Reject</el-button></template><el-button v-if="manager&&!['COMPLETED','CANCELLED'].includes(selected.state)" :disabled="saving" @click="act('CANCEL')">Cancel remaining</el-button></div><h3>Receipts</h3><el-table :data="receipts"><el-table-column prop="quantity" label="QUANTITY"/><el-table-column prop="transactionId" label="MOVEMENT"/><el-table-column prop="actor" label="ACTOR"/></el-table><h3>History</h3><el-timeline><el-timeline-item v-for="(a,i) in history" :key="i" :timestamp="new Date(a.createdAt).toLocaleString()"><b>{{ a.actor }} · {{ a.action }}</b><div>{{ a.note }}</div></el-timeline-item></el-timeline></template></el-dialog>
 <el-dialog v-model="receiveOpen" title="Receive approved stock" width="520px"><el-form label-position="top"><el-form-item label="Quantity"><el-input-number v-model="receipt.quantity" :min="1" :max="1000000000"/></el-form-item><el-form-item label="Batch number"><el-input v-model="receipt.batchNumber" maxlength="80"/></el-form-item><el-form-item label="Production date"><el-date-picker v-model="receipt.productionDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Expiry date"><el-date-picker v-model="receipt.expiryDate" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="receiveOpen=false">Cancel</el-button><el-button type="primary" :loading="saving" @click="receive">Record receipt</el-button></template></el-dialog>
</section></template>
