<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import { api, warnings } from '../api'
import type { Page, Warning, WarningAction, User } from '../types'
import { useRouter } from 'vue-router'
const router=useRouter()
const page=ref<Page<Warning>>(), state=ref('open'), type=ref(''), index=ref(0), loading=ref(false), saving=ref(false)
const selected=ref<Warning>(), history=ref<WarningAction[]>([]), assignees=ref<User[]>([]), open=ref(false), assignee=ref<number>(), note=ref('')
const labels:Record<string,string>={OUT:'Out of stock',LOW:'Low stock',RESTOCKED:'Restocked',EXPIRING:'Near expiry',EXPIRED:'Expired',SLOW:'Slow-moving stock',PENDING:'Pending',CONFIRMED:'Confirmed',PROCESSING:'Processing',RECOVERED:'Recovered'}
const rulesOpen=ref(false), policy=reactive({nearExpiryDays:7,businessTimezone:'Asia/Shanghai',slowStockDays:30,slowStockMinimum:10}),refreshStatus=ref<any>({})
async function configure(){try{Object.assign(policy,(await api.get('/warnings/policy')).data);refreshStatus.value=(await api.get('/warnings/refresh-status')).data;rulesOpen.value=true}catch{ElMessage.error('Could not load rules')}}
async function savePolicy(){saving.value=true;try{await api.put('/warnings/policy',policy);rulesOpen.value=false;await load();ElMessage.success('Rules updated')}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not update rules')}finally{saving.value=false}}
async function refresh(){loading.value=true;try{await api.post('/warnings/refresh');await load()}catch{ElMessage.error('Could not refresh warnings')}finally{loading.value=false}}
async function load(){loading.value=true;try{page.value=await warnings({state:state.value,type:type.value,page:index.value,size:20})}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not load warnings')}finally{loading.value=false}}
watch([state,type],()=>{index.value=0;load()});watch(index,load);onMounted(load)
const timer=setInterval(()=>{if(!open.value&&!rulesOpen.value&&!loading.value)load()},30000)
onUnmounted(()=>clearInterval(timer))
async function inspect(w:Warning){selected.value=w;assignee.value=w.assignedToId;note.value='';open.value=true;try{history.value=(await api.get(`/warnings/${w.id}/history`)).data;assignees.value=(await api.get('/warnings/assignees')).data}catch{ElMessage.error('Could not load warning history')}}
async function act(action:string){if(!selected.value||saving.value)return;if(action!=='CONFIRM'&&!note.value.trim())return ElMessage.warning('Add a handling note');saving.value=true;try{const id=selected.value.id;selected.value=(await api.post(`/warnings/${id}/${action==='CONFIRM'?'ack':'actions'}`,action==='CONFIRM'?{}:{action,assigneeId:assignee.value??null,note:note.value})).data;history.value=(await api.get(`/warnings/${id}/history`)).data;note.value='';await load();ElMessage.success('Warning updated')}catch(e:any){ElMessage.error(e.response?.data?.message||'Could not update warning')}finally{saving.value=false}}
</script>
<template>
 <section class="view table-view" v-loading="loading">
  <div class="page-heading"><h1>Warning center</h1><div class="feature-actions"><el-button @click="configure">Rules</el-button><el-button @click="refresh">Recheck stock</el-button></div></div>
  <div class="surface-card table-surface">
   <div class="table-toolbar feature-toolbar"><el-select v-model="state" aria-label="Warning state"><el-option label="Active warnings" value="open"/><el-option label="Recovered history" value="resolved"/><el-option label="All events" value="all"/></el-select><el-select v-model="type" aria-label="Warning type"><el-option label="All types" value=""/><el-option v-for="t in ['OUT','LOW','EXPIRING','EXPIRED','SLOW','RESTOCKED']" :key="t" :label="labels[t]" :value="t"/></el-select><span>{{ page?.totalElements||0 }} events</span></div>
   <el-table :data="page?.items||[]" stripe><el-table-column label="PRODUCT" min-width="220"><template #default="{row}"><b>{{ row.productName }}</b><div>{{ row.sku }}<span v-if="row.batchNumber"> · {{ row.batchNumber }}</span></div></template></el-table-column><el-table-column label="WARNING" width="160"><template #default="{row}"><el-tag :type="row.severity==='CRITICAL'?'danger':row.type==='RESTOCKED'?'success':'warning'">{{ labels[row.type] }}</el-tag></template></el-table-column><el-table-column prop="severity" label="SEVERITY" width="110"/><el-table-column label="STATUS" width="140"><template #default="{row}">{{ labels[row.reviewStage] }}</template></el-table-column><el-table-column label="ASSIGNED TO" min-width="140"><template #default="{row}">{{ row.assignedTo||'Unassigned' }}</template></el-table-column><el-table-column prop="quantity" label="QUANTITY" width="110"/><el-table-column width="120"><template #default="{row}"><el-button @click="inspect(row)">Handle</el-button></template></el-table-column><template #empty>No warnings</template></el-table>
   <div class="table-pagination"><span>{{ page?.totalElements||0 }} events</span><el-pagination :current-page="index+1" @current-change="index=$event-1" :page-size="20" :total="page?.totalElements||0" layout="prev, pager, next"/></div>
  </div>
  <el-dialog v-model="open" :title="selected?.productName||'Warning'" width="680px">
   <template v-if="selected"><div class="feature-facts"><span>{{ labels[selected.type] }} · {{ selected.severity }}</span><span>{{ labels[selected.reviewStage] }}</span><span>Quantity {{ selected.quantity }} / threshold {{ selected.threshold }}</span><span v-if="selected.expiryDate">Expiry {{ selected.expiryDate }}</span><span v-if="selected.previousId">Previous event #{{ selected.previousId }}</span></div>
    <el-form label-position="top"><el-form-item label="Assigned team member"><el-select v-model="assignee" clearable :disabled="selected.state==='RESOLVED'"><el-option v-for="u in assignees" :key="u.id" :label="u.displayName" :value="u.id"/></el-select></el-form-item><el-form-item label="Handling note"><el-input v-model="note" type="textarea" :rows="3" maxlength="1000"/></el-form-item></el-form>
    <div class="feature-actions"><el-button v-if="selected.state==='OPEN'&&!selected.acknowledgedBy" :loading="saving" @click="act('CONFIRM')">Confirm</el-button><el-button v-if="selected.state==='OPEN'" :disabled="saving" @click="act('ASSIGN')">Save assignment</el-button><el-button v-if="selected.state==='OPEN'&&selected.reviewStage!=='PROCESSING'" type="primary" :disabled="saving" @click="act('PROCESS')">Start handling</el-button><el-button :disabled="saving" @click="act('NOTE')">Add note</el-button></div>
    <h3>History</h3><el-timeline><el-timeline-item v-for="a in history" :key="a.id" :timestamp="new Date(a.createdAt).toLocaleString()"><b>{{ a.actor }} · {{ a.action }}</b><div>{{ a.note }}</div></el-timeline-item></el-timeline>
    <el-button v-if="selected.state==='OPEN'&&['OUT','LOW'].includes(selected.type)" @click="router.push({path:'/',query:{view:'purchases',productId:selected.productId,warningId:selected.id}})">Replenish stock</el-button>
   </template>
  </el-dialog>
  <el-dialog v-model="rulesOpen" title="Warning rules" width="520px"><el-form label-position="top"><el-form-item label="Near-expiry window (days)"><el-input-number v-model="policy.nearExpiryDays" :min="0" :max="365"/></el-form-item><el-form-item label="No-sales observation window (days)"><el-input-number v-model="policy.slowStockDays" :min="1" :max="3650"/></el-form-item><el-form-item label="Minimum sellable stock for slow-stock warning"><el-input-number v-model="policy.slowStockMinimum" :min="1" :max="1000000000"/></el-form-item><el-form-item label="Business time zone"><el-input v-model="policy.businessTimezone"/></el-form-item></el-form><div class="feature-facts"><span>Scheduled check: every {{ refreshStatus.intervalSeconds||30 }} seconds</span><span>Failed products: {{ refreshStatus.failedProducts||0 }}</span></div><template #footer><el-button @click="rulesOpen=false">Cancel</el-button><el-button type="primary" :loading="saving" @click="savePolicy">Save rules</el-button></template></el-dialog>
 </section>
</template>
