export type Role = 'ADMIN' | 'MANAGER' | 'CLERK'
export interface User { id: number; username: string; displayName: string; role: Role; enabled: boolean; createdAt: string }
export interface Product { id: number; sku: string; barcode: string | null; name: string; unit: string; price: number; quantity: number; sellableQuantity: number; safetyStock: number; reorderThreshold: number; category: string | null; supplier: string | null; active: boolean; updatedAt: string }
export interface Batch { id: number; productId: number; productName: string; sku: string; batchNumber: string; receivedDate: string; productionDate?: string; expiryDate?: string; quantity: number; quarantined: boolean; status: string }
export interface Transaction { id: number; productId: number; productName: string; type: 'STOCK_IN' | 'STOCK_OUT' | 'SALE' | 'ADJUSTMENT' | 'STOCKTAKE'; delta: number; quantityBefore: number; quantityAfter: number; reason: string; actor: string; createdAt: string }
export interface Warning { id: number; productId: number; sku: string; productName: string; type: 'LOW' | 'OUT' | 'RESTOCKED' | 'EXPIRING' | 'EXPIRED' | 'SLOW'; state: 'OPEN' | 'RESOLVED'; quantity: number; threshold: number; acknowledgedBy: string | null; acknowledgedAt: string | null; createdAt: string; expiresAt: string; reviewStage: 'PENDING' | 'CONFIRMED' | 'PROCESSING' | 'RECOVERED'; severity: string; assignedToId?: number; assignedTo?: string; recoveredAt?: string; previousId?: number; batchId?: number; batchNumber?: string; expiryDate?: string }
export interface WarningAction { id: number; action: string; note: string; actor: string; createdAt: string }
export interface Page<T> { items: T[]; page: number; size: number; totalElements: number; totalPages: number }
export interface Category { id: number; name: string; description: string; active: boolean }
export interface Supplier { id: number; name: string; contactName: string; email: string; phone: string; active: boolean }
export interface Dashboard { productCount: number; lowStock: number; outOfStock: number; inventoryValue: number; transactionCount: number; activityDates: string[]; activityCounts: number[]; categoryMix: { name: string; quantity: number; productCount: number }[]; urgentProducts: Product[]; warnings: Warning[]; activeWarningCount: number }
