import { chromium } from '../frontend/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const envText=await fs.readFile(path.join(root,'.env'),'utf8');
const password=process.env.DEMO_PASSWORD||envText.match(/^DEMO_PASSWORD=(.*)$/m)?.[1]?.replace(/^["']|["']$/g,'');
if(!password)throw new Error('Set DEMO_PASSWORD.');
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1.5});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const result={timestamp_utc:new Date().toISOString(),checks:[],screenshots:[],consoleErrors:errors};
const base=process.env.SHELFWISE_WEB||'http://localhost:5173';
const output=path.join(root,'thesis','figures');await fs.mkdir(output,{recursive:true});
async function screenshot(name){const target=path.join(output,name+'.png');if(name==='ui-stock-form')await page.getByRole('dialog',{name:'Record stock activity'}).screenshot({path:target});else if(name==='ui-login')await page.locator('.login-form-wrap').screenshot({path:target});else if(['ui-dashboard','ui-inventory','ui-warnings','ui-reports','ui-history','ui-team'].includes(name)){const box=await page.locator('.page-content').boundingBox();await page.screenshot({path:target,clip:{x:box.x+20,y:box.y+20,width:box.width-40,height:name==='ui-dashboard'?555:530}})}else await page.screenshot({path:target,fullPage:false});result.screenshots.push(name+'.png')}
async function settle(){await page.waitForLoadState('networkidle');await page.locator('.el-loading-mask').waitFor({state:'hidden'}).catch(()=>{});}
async function signIn(username){await page.goto(base+'/login');await settle();await page.locator('#username').fill(username);await page.locator('#password').fill(password);await page.getByRole('button',{name:'Sign in to Shelfwise'}).click();await page.waitForURL(url=>url.pathname!='/login');await settle();}
await page.goto(base+'/login');await settle();await screenshot('ui-login');
await signIn('admin');await page.getByRole('heading',{name:/Good /}).waitFor();await screenshot('ui-dashboard');result.checks.push('administrator dashboard renders authenticated MySQL metrics');
for(const [view,name] of [['inventory','ui-inventory'],['warnings','ui-warnings'],['transactions','ui-history'],['reports','ui-reports'],['team','ui-team']]){await page.goto(base+'/?view='+view);await settle();await screenshot(name);result.checks.push(view+' view renders');}
await page.goto(base+'/?view=inventory');await settle();await page.getByPlaceholder('Search product, SKU or barcode').fill('zz-no-such-product');await settle();await page.getByText('No products match those filters').waitFor();result.checks.push('empty search displays a recovery state');await page.getByPlaceholder('Search product, SKU or barcode').fill('');await settle();
await page.goto(base+'/?view=transactions');await settle();await page.getByRole('button',{name:'Record activity',exact:true}).click();await page.getByRole('dialog',{name:'Record stock activity'}).waitFor();await screenshot('ui-stock-form');const dialog=page.getByRole('dialog',{name:'Record stock activity'});await dialog.getByRole('combobox').first().click();await page.getByRole('option').filter({hasText:'Apples, Gala'}).click();await dialog.getByRole('spinbutton').fill('2');await dialog.locator('textarea').fill('Browser acceptance delivery');const posted=page.waitForResponse(r=>r.url().endsWith('/api/transactions')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Record activity',exact:true}).click();const postedResponse=await posted;if(postedResponse.status()!==201)throw new Error('Browser stock movement failed');const movement=await postedResponse.json();if(movement.quantityAfter-movement.quantityBefore!==2)throw new Error('Browser stock delta incorrect');await dialog.waitFor({state:'hidden'});result.checks.push('browser submits a stock receipt with actor, reason and correct before/after delta');
await context.clearCookies();await signIn('clerk');await page.goto(base+'/?view=warnings');await settle();if(new URL(page.url()).searchParams.get('view')!=='inventory')throw new Error('Clerk reached warning view');result.checks.push('clerk navigation guard redirects warning deep link');
await page.goto(base+'/?view=transactions');await settle();await page.getByRole('button',{name:'Record activity',exact:true}).waitFor();result.checks.push('clerk can open audited stock form');
await context.clearCookies();await signIn('manager');await page.goto(base+'/?view=warnings');await settle();await page.getByRole('heading',{name:'Stock warnings',exact:true}).waitFor();const ackButton=page.getByRole('button',{name:'Acknowledge',exact:true}).first();if(await ackButton.count()){const ack=page.waitForResponse(r=>r.url().includes('/ack')&&r.request().method()==='POST');await ackButton.click();const ackResponse=await ack;if(ackResponse.status()!==200)throw new Error('Warning acknowledgement failed');result.checks.push('manager acknowledges an open warning through the board');}result.checks.push('manager can review warning view');await page.goto(base+'/?view=team');await settle();if(new URL(page.url()).searchParams.get('view')!=='inventory')throw new Error('Manager reached team access');result.checks.push('manager cannot reach team administration');
await page.setViewportSize({width:390,height:844});await page.goto(base+'/?view=inventory');await settle();await screenshot('ui-mobile-inventory');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);if(overflow)throw new Error('Mobile page overflows viewport');result.checks.push('390px mobile page confines table scrolling to its container');
if(errors.length)throw new Error('Browser runtime errors: '+errors.join('; '));
await browser.close();await fs.mkdir(path.join(root,'docs','evidence'),{recursive:true});await fs.writeFile(path.join(root,'docs','evidence','browser-smoke.json'),JSON.stringify(result,null,2));console.log('PASS',result.checks.length,'browser checks;',result.screenshots.length,'screenshots;',errors.length,'runtime errors');
