<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, categories, dashboard as loadDashboard, products, suppliers, transactions, warnings, users, stockSummary } from '../api'
import { useAuthStore } from '../stores/auth'
import type { Category, Dashboard, Page, Product, Supplier, Transaction, User, Warning } from '../types'
import { stockStatusLabel } from '../inventory'
import VueECharts from 'vue-echarts'
import WarningCenter from '../components/WarningCenter.vue'
import BatchInventory from '../components/BatchInventory.vue'
import { use } from 'echarts/core'
import { LineChart, PieChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
use([LineChart, PieChart, GridComponent, TooltipComponent, LegendComponent, CanvasRenderer])

const route=useRoute(),router=useRouter(),auth=useAuthStore()
const section=computed(()=>String(route.query.view||'overview'))
const isAdmin=computed(()=>auth.user?.role==='ADMIN')
const isManager=computed(()=>auth.user?.role==='MANAGER'||isAdmin.value)
const pageTitle=computed(()=>({overview:'Overview',inventory:'Inventory',batches:'Batch inventory',transactions:'Stock activity',warnings:'Stock warnings',reports:'Reports & insights',products:'Product catalogue',categories:'Categories',suppliers:'Suppliers',team:'Team access',settings:'Store settings'} as Record<string,string>)[section.value]||'Overview')
const navItems=computed(()=>[{id:'overview',label:'Overview',icon:'DataBoard'},{id:'inventory',label:'Inventory',icon:'Goods'},{id:'batches',label:'Batches',icon:'Collection'},{id:'transactions',label:'Stock activity',icon:'Sort'},...(isManager.value?[{id:'warnings',label:'Stock warnings',icon:'Bell',badge:summary.value?.lowStock||summary.value?.outOfStock||0},{id:'reports',label:'Reports & insights',icon:'TrendCharts'}]:[])])
const catalogItems=[{id:'products',label:'Products',icon:'Box'},{id:'categories',label:'Categories',icon:'Collection'},{id:'suppliers',label:'Suppliers',icon:'Van'}]
const adminItems=[{id:'team',label:'Team access',icon:'User'},{id:'settings',label:'Store settings',icon:'Setting'}]
const summary=ref<Dashboard|null>(null),productPage=ref<Page<Product>|null>(null),transactionPage=ref<Page<Transaction>|null>(null),warningPage=ref<Page<Warning>|null>(null)
const categoryList=ref<Category[]>([]),supplierList=ref<Supplier[]>([]),userList=ref<User[]>([]),report=ref<Record<string,any>>({})
const loading=ref(false),search=ref(''),statusFilter=ref(''),categoryFilter=ref<number|undefined>(),currentPage=ref(0),warningFilter=ref('open')
const thresholdOnly=ref(false)
const productDialog=ref(false),movementDialog=ref(false),userDialog=ref(false),categoryDialog=ref(false),supplierDialog=ref(false)
const productForm=reactive({id:0,sku:'',barcode:'',name:'',unit:'pcs',price:0,safetyStock:0,reorderThreshold:0,categoryId:undefined as number|undefined,supplierId:undefined as number|undefined})
const movementForm=reactive({productId:undefined as number|undefined,type:'STOCK_IN',quantity:1,reason:'',batchNumber:'',productionDate:null as string|null,expiryDate:null as string|null})
const userForm=reactive({username:'',displayName:'',password:'',role:'CLERK'})
const catalogEditId=ref(0)
const categoryForm=reactive({name:'',description:''}),supplierForm=reactive({name:'',contactName:'',email:'',phone:''})
const saving=ref(false),movementRequestKey=ref('')
const currency=ref('USD')
const currencyFormat=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:currency.value,maximumFractionDigits:2}).format(value)
const timeFormat=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))
const movementLabel=(type:string)=>({STOCK_IN:'Stock received',STOCK_OUT:'Stock dispatched',ADJUSTMENT:'Stock adjustment',STOCKTAKE:'Stock count'} as Record<string,string>)[type]||type
const statusLabel=(p:Product)=>stockStatusLabel(p.sellableQuantity,p.reorderThreshold)
const warningLabel=(w:Warning)=>w.type==='OUT'?'Out of stock':w.type==='LOW'?'Low stock':'Recently restocked'
const trendOption=computed(()=>({animation:false,grid:{left:48,right:18,top:22,bottom:32},tooltip:{trigger:'axis',backgroundColor:'#fff',borderColor:'#e7eaf0',textStyle:{color:'#17233a'}},xAxis:{type:'category',boundaryGap:false,data:(summary.value?.activityDates||[]).map(d=>new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(new Date(`${d}T12:00:00Z`))),axisLine:{show:false},axisTick:{show:false},axisLabel:{color:'#8993a5'},splitLine:{show:false}},yAxis:{type:'value',name:'entries',nameTextStyle:{color:'#8993a5',fontSize:9},minInterval:1,axisLabel:{color:'#8993a5',fontSize:9},axisLine:{show:false},axisTick:{show:false},splitLine:{lineStyle:{color:'#eef0f4',type:'dashed'}}},series:[{name:'Recorded stock movements',type:'line',smooth:true,symbol:'circle',symbolSize:7,data:summary.value?.activityCounts||[],lineStyle:{width:3,color:'#5068d7'},itemStyle:{color:'#fff',borderColor:'#5068d7',borderWidth:2},areaStyle:{color:'rgba(80,104,215,.12)'}}]}))
const categoryOption=computed(()=>({animation:false,tooltip:{trigger:'item'},legend:{bottom:0,left:'center',itemWidth:8,itemHeight:8,textStyle:{color:'#717c8e',fontSize:10}},series:[{type:'pie',radius:['55%','76%'],center:['50%','42%'],avoidLabelOverlap:true,label:{show:false},itemStyle:{borderColor:'#fff',borderWidth:3},data:(summary.value?.categoryMix||[]).filter(c=>c.quantity>0).map((c,i)=>({value:c.quantity,name:c.name,itemStyle:{color:['#54a884','#7790e6','#e8a65b','#a992cf','#68a7b1'][i%5]}}))}]}))
function go(id:string){router.push({path:'/',query:id==='overview'?{}:{view:id}})}
async function loadAll(){loading.value=true;try{
 if(section.value==='overview'){if(isManager.value)summary.value=await loadDashboard();else summary.value=await stockSummary();const s=await api.get('/settings');currency.value=s.data.currency||'USD'}
 else if(['inventory','products'].includes(section.value)){productPage.value=await products({q:search.value,status:statusFilter.value,categoryId:categoryFilter.value,page:currentPage.value,size:12});categoryList.value=await categories();if(isAdmin.value)supplierList.value=await suppliers()}
 else if(section.value==='transactions')transactionPage.value=await transactions({page:currentPage.value,size:15})
 else if(section.value==='warnings'){summary.value=await loadDashboard()}
 else if(section.value==='reports'){report.value=(await api.get('/reports/summary')).data;summary.value=await loadDashboard()}
 else if(section.value==='categories')categoryList.value=await categories()
 else if(section.value==='suppliers')supplierList.value=await suppliers()
 else if(section.value==='team')userList.value=await users()
 else if(section.value==='settings'){const s=await api.get('/settings');Object.assign(categoryForm,{});businessForm.businessName=s.data.business_name;businessForm.currency=s.data.currency;currency.value=s.data.currency}
 }catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not load this view. Check the connection and retry.')}finally{loading.value=false}}
const businessForm=reactive({businessName:'Neighborhood Market',currency:'USD'})
watch([section,currentPage,warningFilter],()=>loadAll())
watch([search,statusFilter,categoryFilter],()=>{currentPage.value=0;loadAll()})
watch(()=>section.value,()=>{search.value='';statusFilter.value='';categoryFilter.value=undefined;currentPage.value=0})
onMounted(()=>{loadAll();window.addEventListener('shelfwise:unauthenticated',unauthenticated)})
onUnmounted(()=>window.removeEventListener('shelfwise:unauthenticated',unauthenticated))
function unauthenticated(){auth.user=null;router.replace('/login')}
function newProduct(){thresholdOnly.value=false;Object.assign(productForm,{id:0,sku:'',barcode:'',name:'',unit:'pcs',price:0,safetyStock:0,reorderThreshold:0,categoryId:undefined,supplierId:undefined});productDialog.value=true}
function editProduct(p:Product){thresholdOnly.value=!isAdmin.value;Object.assign(productForm,{id:p.id,sku:p.sku,barcode:p.barcode||'',name:p.name,unit:p.unit,price:p.price,safetyStock:p.safetyStock,reorderThreshold:p.reorderThreshold,categoryId:categoryList.value.find(c=>c.name===p.category)?.id,supplierId:supplierList.value.find(s=>s.name===p.supplier)?.id});productDialog.value=true}
async function saveProduct(){if(productForm.safetyStock>productForm.reorderThreshold)return ElMessage.warning('Safety stock must not exceed the reorder threshold.');const body={...productForm};delete (body as any).id;try{if(thresholdOnly.value)await api.patch(`/products/${productForm.id}/thresholds`,{safetyStock:productForm.safetyStock,reorderThreshold:productForm.reorderThreshold});else if(productForm.id)await api.put(`/products/${productForm.id}`,body);else await api.post('/products',body);ElMessage.success(productForm.id?'Product details saved.':'Product added to the catalogue.');productDialog.value=false;loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not save this product.')}}
async function openMovement(p?:Product){if(!productPage.value?.items?.length){try{productPage.value=await products({size:100})}catch{}}Object.assign(movementForm,{productId:p?.id,type:'STOCK_IN',quantity:1,reason:'',batchNumber:'',productionDate:null,expiryDate:null});movementRequestKey.value=crypto.randomUUID();movementDialog.value=true}
async function saveMovement(){if(!movementForm.productId||!movementForm.reason.trim())return ElMessage.warning('Select a product and record a reason.');if(saving.value)return;saving.value=true;try{await api.post('/transactions',{...movementForm,batchNumber:movementForm.type==='STOCK_IN'?movementForm.batchNumber||null:null,productionDate:movementForm.type==='STOCK_IN'?movementForm.productionDate:null,expiryDate:movementForm.type==='STOCK_IN'?movementForm.expiryDate:null,idempotencyKey:movementRequestKey.value});ElMessage.success('Stock activity recorded with an audit trail.');movementDialog.value=false;loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not record this stock activity.')}finally{saving.value=false}}
async function acknowledge(w:Warning){try{await api.post(`/warnings/${w.id}/ack`);ElMessage.success(`${w.productName} warning acknowledged.`);await loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not acknowledge this warning.')}}
async function archiveProduct(p:Product){try{await ElMessageBox.confirm(`Archive “${p.name}”? Its history stays available, but no new stock can be recorded.`, 'Archive product', {confirmButtonText:'Archive product',cancelButtonText:'Cancel',type:'warning'});await api.delete(`/products/${p.id}`);ElMessage.success('Product archived; its history is preserved.');loadAll()}catch{}}
function roleLabel(role:string){return role==='ADMIN'?'Administrator':role==='MANAGER'?'Store manager':'Stock clerk'}
async function saveUser(){try{await api.post('/users',userForm);ElMessage.success('Team account created.');userDialog.value=false;await loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not create this account.')}}
async function toggleUser(u:User){try{await api.patch(`/users/${u.id}/enabled`,{enabled:!u.enabled});ElMessage.success(u.enabled?'Team member access paused.':'Team member access restored.');await loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not update this account.')}}
async function saveCategory(){try{if(catalogEditId.value)await api.put(`/categories/${catalogEditId.value}`,categoryForm);else await api.post('/categories',categoryForm);ElMessage.success('Category created.');categoryDialog.value=false;await loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not create this category.')}}
async function saveSupplier(){try{if(catalogEditId.value)await api.put(`/suppliers/${catalogEditId.value}`,supplierForm);else await api.post('/suppliers',supplierForm);ElMessage.success('Supplier saved.');supplierDialog.value=false;await loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not save this supplier.')}}
async function deleteCatalog(kind:string,id:number,name:string){try{await ElMessageBox.confirm(`Delete ${name}? Referenced records cannot be deleted.`, 'Delete record',{confirmButtonText:'Delete',cancelButtonText:'Cancel'});await api.delete(`/${kind}/${id}`);await loadAll();ElMessage.success('Record deleted.')}catch(e:any){if(e?.response)ElMessage.error(e.response.data?.message||'Could not delete this record.')}}
async function changeRole(u:User,role:string){try{await api.patch(`/users/${u.id}/access`,{role,enabled:u.enabled});ElMessage.success('Access role updated.');await loadAll()}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not update the role.')}}
async function saveSettings(){try{await api.put('/settings',businessForm);ElMessage.success('Store settings saved.')}catch(e:any){ElMessage.error(e?.response?.data?.message||'Could not save settings.')}}
async function signOut(){await auth.signOut();router.replace('/login')}
function exportCsv(){const rows=productPage.value?.items||[];const csv=['SKU,Product,Category,Quantity,Unit,Reorder threshold,Unit price',...rows.map(p=>[p.sku,p.name,p.category||'',p.quantity,p.unit,p.reorderThreshold,p.price].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='shelfwise-inventory.csv';a.click();URL.revokeObjectURL(a.href)}
</script>

<template>
 <div class="workspace">
  <aside class="sidebar"><div class="sidebar-brand"><a class="brand" href="#" @click.prevent="go('overview')"><span class="brand-mark"><el-icon><Goods /></el-icon></span><span>Shelfwise</span></a></div>
   <button class="store-switch" type="button" aria-label="Open store settings" title="Open store settings" @click="go('settings')"><span class="store-avatar">NM</span><span class="store-name"><b>{{ businessForm.businessName||'Neighborhood Market' }}</b></span><el-icon class="store-chevron"><ArrowDown /></el-icon></button>
   <nav class="side-nav" aria-label="Main navigation"><button v-for="item in navItems" :key="item.id" class="nav-item" :class="{active:section===item.id}" @click="go(item.id)"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span><span v-if="item.id==='warnings'&&item.badge" class="nav-count">{{ item.badge }}</span></button>
    <button v-for="item in catalogItems" :key="item.id" class="nav-item" :class="{active:section===item.id||item.id==='products'&&section==='inventory'}" @click="go(item.id)"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span></button>
    <template v-if="isAdmin"><button v-for="item in adminItems" :key="item.id" class="nav-item" :class="{active:section===item.id}" @click="go(item.id)"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span></button></template></nav>
   <div class="sidebar-bottom"><button class="profile-button" type="button" aria-label="Sign out" title="Sign out" @click="signOut"><span class="profile-avatar">{{ auth.user?.displayName.split(' ').map(x=>x[0]).slice(0,2).join('') }}</span><span class="profile-info"><b>{{ auth.user?.displayName }}</b><small>{{ roleLabel(auth.user?.role||'CLERK') }}</small></span><el-icon class="logout-icon"><SwitchButton /></el-icon></button></div>
  </aside>
  <main class="main-area"><header class="topbar"><div class="breadcrumb"><span>Workspace</span><el-icon><ArrowRight /></el-icon><b>{{ pageTitle }}</b></div><div class="topbar-right"><span class="today-label"><el-icon><Calendar /></el-icon>{{ new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date()) }}</span><button v-if="isManager" class="icon-action" type="button" aria-label="View stock warnings" title="View stock warnings" @click="go('warnings')"><el-icon><Bell /></el-icon><i v-if="summary?.lowStock||summary?.outOfStock" class="notification-dot"></i></button><button class="top-avatar" type="button" aria-label="Open store settings" title="Open store settings" @click="go('settings')">{{ auth.user?.displayName.split(' ').map(x=>x[0]).slice(0,2).join('') }}</button></div></header>
   <div class="page-content" v-loading="loading" element-loading-background="rgba(248,249,252,.72)">
    <section v-if="section==='overview'" class="view overview-view"><div class="page-heading"><div><span class="eyebrow">{{ new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase() }}</span><h1>Good {{ new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening' }}, {{ auth.user?.displayName.split(' ')[0] }} <span class="wave"></span></h1><p>Here’s how your shelves are looking today.</p></div><div class="heading-actions"><el-button v-if="isManager" @click="go('reports')"><el-icon><TrendCharts /></el-icon>View reports</el-button><el-button v-if="auth.user?.role!=='MANAGER'" type="primary" @click="openMovement()"><el-icon><Plus /></el-icon>Record stock</el-button></div></div>
     <div class="metric-grid"><article class="metric-card"><div class="metric-top"><span class="metric-icon metric-indigo"><el-icon><Goods /></el-icon></span><span class="metric-context">ACTIVE CATALOGUE</span><button class="metric-menu" aria-label="Inventory options" @click="go('inventory')"><el-icon><MoreFilled /></el-icon></button></div><div class="metric-number">{{ summary?.productCount??'—' }}<span class="metric-unit">products</span></div><div class="metric-foot"><span class="foot-dot dot-indigo"></span><span>Across your store catalogue</span></div></article>
      <article class="metric-card"><div class="metric-top"><span class="metric-icon metric-amber"><el-icon><WarningFilled /></el-icon></span><span class="metric-context">NEEDS REORDERING</span><span class="metric-menu"><el-icon><MoreFilled /></el-icon></span></div><div class="metric-number">{{ summary?.lowStock??'—' }}<span class="metric-unit">items</span></div><button class="metric-foot metric-link" @click="go('warnings')"><span class="foot-dot dot-amber"></span><span>{{ summary?.outOfStock||0 }} out of stock <el-icon><ArrowRight /></el-icon></span></button></article>
      <article class="metric-card"><div class="metric-top"><span class="metric-icon metric-green"><el-icon><Money /></el-icon></span><span class="metric-context">INVENTORY VALUE</span><span class="metric-menu"><el-icon><MoreFilled /></el-icon></span></div><div class="metric-number metric-money">{{ currencyFormat(summary?.inventoryValue||0) }}</div><div class="metric-foot"><span class="foot-dot dot-green"></span><span>At current unit prices</span></div></article>
      <article class="metric-card"><div class="metric-top"><span class="metric-icon metric-blue"><el-icon><Sort /></el-icon></span><span class="metric-context">RECORDED MOVEMENTS</span><span class="metric-menu"><el-icon><MoreFilled /></el-icon></span></div><div class="metric-number">{{ summary?.transactionCount??'—' }}<span class="metric-unit">entries</span></div><button class="metric-foot metric-link" @click="go('transactions')"><span class="foot-dot dot-blue"></span><span>Complete activity history <el-icon><ArrowRight /></el-icon></span></button></article></div>
     <div class="overview-grid"><article class="surface-card trend-card"><div class="card-heading"><div><span class="eyebrow">INVENTORY ACTIVITY</span><h2>Recorded stock movements</h2></div><el-select model-value="7 days" size="small" aria-label="Chart time range" style="width:110px"><el-option label="7 days" value="7 days" /></el-select></div><div class="chart-legend"><span class="legend-line"></span>Movements <span class="legend-period">Last 7 days · UTC</span></div><VueECharts :option="trendOption" autoresize class="trend-chart" aria-label="Recorded stock movements per day, last seven days" /></article>
      <article class="surface-card category-card"><div class="card-heading"><div><span class="eyebrow">STOCK MIX</span><h2>By category</h2></div><button class="subtle-icon" aria-label="View inventory by category" @click="go('inventory')"><el-icon><ArrowRight /></el-icon></button></div><div class="category-chart-wrap"><VueECharts :option="categoryOption" autoresize class="category-chart" aria-label="Inventory composition by category"/><div class="donut-center"><b>{{ summary?.categoryMix?.reduce((n,c)=>n+c.quantity,0)||0 }}</b><span>units</span></div></div></article></div>
     <div class="overview-bottom"><article class="surface-card attention-card"><div class="card-heading"><div><span class="eyebrow">PRIORITY LIST</span><h2>Needs your attention</h2></div><button class="text-link" @click="go('warnings')">All warnings <el-icon><ArrowRight /></el-icon></button></div><div v-if="!summary?.warnings?.length" class="empty-state"><span class="empty-icon"><el-icon><CircleCheck /></el-icon></span><b>All caught up</b><span>No open stock warnings to review.</span></div><div v-else class="attention-list"><div v-for="(w,index) in summary.warnings.slice(0,4)" :key="w.id" class="attention-row"><span class="attention-symbol" :class="w.type==='OUT'?'symbol-red':'symbol-amber'"><el-icon><CircleCloseFilled v-if="w.type==='OUT'"/><WarningFilled v-else/></el-icon></span><div class="attention-product"><b>{{ w.productName }}</b><span>{{ w.sku }} <i>·</i> {{ warningLabel(w) }}</span></div><div class="attention-stock"><b>{{ w.quantity }} <small>left</small></b><span>Reorder at {{ w.threshold }}</span></div><button v-if="isManager&&!w.acknowledgedBy" class="ack-small" @click="acknowledge(w)">Review <el-icon><ArrowRight /></el-icon></button><span v-else class="acknowledged-label"><el-icon><CircleCheck /></el-icon>{{ w.acknowledgedBy?'Reviewed':'Open' }}</span></div></div></article>
      <article class="surface-card quick-card"><div class="card-heading"><div><span class="eyebrow">QUICK ACTIONS</span><h2>Get things done</h2></div></div><button v-if="auth.user?.role!=='MANAGER'" class="quick-action" @click="openMovement()"><span class="quick-icon quick-in"><el-icon><Bottom /></el-icon></span><span><b>Receive stock</b><small>Log an incoming delivery</small></span><el-icon class="quick-arrow"><ArrowRight /></el-icon></button><button v-if="auth.user?.role!=='MANAGER'" class="quick-action" @click="openMovement().then(()=>movementForm.type='ADJUSTMENT')"><span class="quick-icon quick-adjust"><el-icon><Operation /></el-icon></span><span><b>Adjust inventory</b><small>Record a count or correction</small></span><el-icon class="quick-arrow"><ArrowRight /></el-icon></button><button class="quick-action" @click="go('inventory')"><span class="quick-icon quick-find"><el-icon><Search /></el-icon></span><span><b>Find a product</b><small>Search your stock list</small></span><el-icon class="quick-arrow"><ArrowRight /></el-icon></button></article></div>
     <div class="view-footnote"><span class="live-dot"></span>Stock position updated live from recorded transactions <span>·</span> All amounts in {{ currency }}</div>
    </section>
    <section v-else-if="section==='inventory'||section==='products'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">{{ section==='products'?'CATALOGUE':'STOCK CONTROL' }}</span><h1>{{ section==='products'?'Product catalogue':'Inventory' }}</h1><p>Search, review and manage the stock on your shelves.</p></div><div class="heading-actions"><el-button @click="exportCsv"><el-icon><Download /></el-icon>Export CSV</el-button><el-button v-if="isAdmin" type="primary" @click="newProduct"><el-icon><Plus /></el-icon>Add product</el-button></div></div>
     <div class="surface-card table-surface"><div class="table-toolbar"><el-input v-model="search" clearable placeholder="Search product, SKU or barcode" class="search-input"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-select v-model="statusFilter" clearable placeholder="All stock levels" class="filter-select"><el-option label="In stock" value="healthy"/><el-option label="Low stock" value="low"/><el-option label="Out of stock" value="out"/></el-select><el-select v-model="categoryFilter" clearable placeholder="All categories" class="filter-select"><el-option v-for="c in categoryList" :key="c.id" :label="c.name" :value="c.id"/></el-select><span class="result-count">{{ productPage?.totalElements||0 }} products</span></div>
      <el-table :data="productPage?.items||[]" row-key="id" stripe class="product-table"><el-table-column label="PRODUCT" min-width="260"><template #default="{row}"><div class="product-cell"><span class="product-thumb" :class="`thumb-${row.id%5}`"><el-icon><component :is="['Apple','ColdDrink','Coffee','Grape','Food'][row.id%5]"/></el-icon></span><span><b>{{ row.name }}</b><small>{{ row.sku }} <i v-if="row.barcode">· {{ row.barcode }}</i></small></span></div></template></el-table-column><el-table-column prop="category" label="CATEGORY" min-width="140"><template #default="{row}"><span class="category-pill">{{ row.category||'Uncategorised' }}</span></template></el-table-column><el-table-column label="ON HAND" width="140" sortable><template #default="{row}"><span class="quantity-cell"><b>{{ row.quantity }}</b> {{ row.unit }}<small>Reorder at {{ row.reorderThreshold }}</small></span></template></el-table-column><el-table-column label="STATUS" width="150"><template #default="{row}"><span class="status-pill" :class="row.quantity===0?'status-out':row.quantity<=row.reorderThreshold?'status-low':'status-good'"><i></i>{{ statusLabel(row) }}</span></template></el-table-column><el-table-column label="UNIT PRICE" width="125" align="right"><template #default="{row}"><span class="price-cell">{{ currencyFormat(row.price) }}</span></template></el-table-column><el-table-column v-if="isAdmin||isManager" label="" width="110" align="right"><template #default="{row}"><el-dropdown trigger="click"><button class="row-menu" aria-label="Product actions"><el-icon><MoreFilled /></el-icon></button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="editProduct(row)">{{ isAdmin?'Edit details':'Edit thresholds' }}</el-dropdown-item><el-dropdown-item v-if="isAdmin" @click="openMovement(row)">Record stock</el-dropdown-item><el-dropdown-item v-if="isAdmin" divided @click="archiveProduct(row)">Archive product</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column><template #empty><div class="table-empty"><el-icon><Search /></el-icon><b>No products match those filters</b><span>Try a different search term or clear one of the filters.</span><el-button link type="primary" @click="search='';statusFilter='';categoryFilter=undefined">Clear filters</el-button></div></template></el-table><div class="table-pagination"><span>Showing {{ (productPage?.items.length||0)?currentPage*12+1:0 }}–{{ currentPage*12+(productPage?.items.length||0) }} of {{ productPage?.totalElements||0 }} items</span><el-pagination :current-page="currentPage+1" @current-change="currentPage=$event-1" :page-size="12" :total="productPage?.totalElements||0" layout="prev, pager, next" background /></div></div><div class="table-note"><el-icon><InfoFilled /></el-icon>Only stock transactions change quantity. Product edits preserve the inventory history.</div>
    </section>
    <section v-else-if="section==='transactions'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">AUDIT TRAIL</span><h1>Stock activity</h1><p>Every stock movement, adjustment and count in one place.</p></div><el-button v-if="auth.user?.role!=='MANAGER'" type="primary" @click="openMovement()"><el-icon><Plus /></el-icon>Record activity</el-button></div><div class="surface-card table-surface"><div class="table-toolbar"><div class="history-intro"><span class="activity-icon"><el-icon><Sort /></el-icon></span><span><b>Inventory history</b><small>Changes are attributed to a team member and reason.</small></span></div><span class="result-count">{{ transactionPage?.totalElements||0 }} entries</span></div><el-table :data="transactionPage?.items||[]" stripe><el-table-column label="ACTIVITY" min-width="230"><template #default="{row}"><span class="movement-cell"><i :class="row.delta>=0?'movement-positive':'movement-negative'"><el-icon><component :is="row.delta>=0?'Top':'Bottom'"/></el-icon></i><span><b>{{ movementLabel(row.type) }}</b><small>{{ row.productName }}</small></span></span></template></el-table-column><el-table-column label="CHANGE" width="130"><template #default="{row}"><span class="delta-value" :class="row.delta>=0?'delta-plus':'delta-minus'">{{ row.delta>0?'+':'' }}{{ row.delta }}</span></template></el-table-column><el-table-column label="BEFORE / AFTER" width="160"><template #default="{row}"><span class="before-after">{{ row.quantityBefore }} <i>→</i> <b>{{ row.quantityAfter }}</b></span></template></el-table-column><el-table-column label="RECORDED BY" width="150"><template #default="{row}"><span class="actor-cell"><i>{{ row.actor.split(' ').map((x:string)=>x[0]).slice(0,2).join('') }}</i>{{ row.actor }}</span></template></el-table-column><el-table-column prop="reason" label="REASON" min-width="190" show-overflow-tooltip/><el-table-column label="DATE & TIME" width="160"><template #default="{row}"><span class="date-cell">{{ timeFormat(row.createdAt) }}</span></template></el-table-column><template #empty><div class="table-empty"><b>No stock activity recorded yet</b><span>When your team receives, dispatches or counts stock, the audit trail appears here.</span></div></template></el-table><div class="table-pagination"><span>{{ transactionPage?.totalElements||0 }} recorded events</span><el-pagination :current-page="currentPage+1" @current-change="currentPage=$event-1" :page-size="15" :total="transactionPage?.totalElements||0" layout="prev, pager, next" background /></div></div></section>
    <BatchInventory v-else-if="section==='batches'" />
    <WarningCenter v-else-if="section==='warnings'" />
    <section v-else-if="section==='reports'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">STORE PERFORMANCE</span><h1>Reports & insights</h1><p>A clear picture of the inventory your store is carrying.</p></div><el-button @click="go('inventory')"><el-icon><Goods /></el-icon>View inventory</el-button></div><div class="report-metrics"><div class="report-metric surface-card"><span>ESTIMATED INVENTORY VALUE</span><b>{{ currencyFormat(report.inventoryValue||0) }}</b><small>Current quantity × unit price</small></div><div class="report-metric surface-card"><span>ACTIVE PRODUCTS</span><b>{{ report.activeProducts||0 }}</b><small>Products in the current catalogue</small></div><div class="report-metric surface-card"><span>BELOW REORDER LEVEL</span><b class="report-warn">{{ report.lowStock||0 }}</b><small>{{ report.outOfStock||0 }} additional items are out of stock</small></div><div class="report-metric surface-card"><span>ALL-TIME MOVEMENTS</span><b>{{ report.totalMovements||0 }}</b><small>{{ report.movementsToday||0 }} recorded today</small></div></div><div class="overview-grid"><article class="surface-card trend-card"><div class="card-heading"><div><span class="eyebrow">INVENTORY ACTIVITY</span><h2>Recorded movements per day</h2></div></div><p class="report-disclaimer">Counts use recorded timestamps in UTC; zero-activity days appear as zero.</p><VueECharts :option="trendOption" autoresize class="trend-chart report-trend" aria-label="Recorded stock movements per day"/></article><article class="surface-card category-card"><div class="card-heading"><div><span class="eyebrow">STOCK MIX</span><h2>By category</h2></div></div><VueECharts :option="categoryOption" autoresize class="category-chart report-pie" aria-label="Illustrative inventory category mix"/><p class="report-disclaimer">Current unit counts grouped by category.</p></article></div><div class="table-note"><el-icon><InfoFilled /></el-icon>Inventory value uses current unit prices as a simple estimate, not supplier cost or accounting valuation.</div></section>
    <section v-else-if="section==='categories'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">PRODUCT ORGANISATION</span><h1>Categories</h1><p>Keep the catalogue organised around how your team works.</p></div><el-button v-if="isAdmin" type="primary" @click="catalogEditId=0;Object.assign(categoryForm,{name:'',description:''});categoryDialog=true"><el-icon><Plus /></el-icon>Add category</el-button></div><div class="category-card-grid"><article v-for="(c,i) in categoryList" :key="c.id" class="surface-card catalog-card"><span class="catalog-icon" :class="`catalog-color-${i%4}`"><el-icon><component :is="['Apple','MilkTea','Box','Collection'][i%4]"/></el-icon></span><span class="eyebrow">CATEGORY {{ String(i+1).padStart(2,'0') }}</span><h2>{{ c.name }}</h2><div v-if="isAdmin" class="catalog-edit-actions"><el-button size="small" link @click="catalogEditId=c.id;Object.assign(categoryForm,c);categoryDialog=true">Edit</el-button><el-button size="small" link @click="deleteCatalog('categories',c.id,c.name)">Delete</el-button></div><p>{{ c.description||'No category description has been added.' }}</p><button class="text-link" @click="categoryFilter=c.id;go('inventory')">Browse products <el-icon><ArrowRight /></el-icon></button></article><div v-if="!categoryList.length" class="surface-card category-empty"><el-icon><Collection /></el-icon><b>No categories yet</b><span>Add a category to group your product catalogue.</span></div></div></section>
    <section v-else-if="section==='suppliers'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">SUPPLY DIRECTORY</span><h1>Suppliers</h1><p>Keep your product partners and contact details in one place.</p></div><el-button v-if="isAdmin" type="primary" @click="catalogEditId=0;Object.assign(supplierForm,{name:'',contactName:'',email:'',phone:''});supplierDialog=true"><el-icon><Plus /></el-icon>Add supplier</el-button></div><div class="supplier-grid"><article v-for="s in supplierList" :key="s.id" class="surface-card supplier-card"><span class="supplier-avatar">{{ s.name.split(' ').map(x=>x[0]).slice(0,2).join('') }}</span><span class="supplier-active"><i></i>Active</span><h2>{{ s.name }}</h2><div v-if="isAdmin" class="catalog-edit-actions"><el-button size="small" link @click="catalogEditId=s.id;Object.assign(supplierForm,s);supplierDialog=true">Edit</el-button><el-button size="small" link @click="deleteCatalog('suppliers',s.id,s.name)">Delete</el-button></div><p>{{ s.contactName||'Primary contact not set' }}</p><div class="supplier-contact"><span v-if="s.email"><el-icon><Message /></el-icon>{{ s.email }}</span><span v-if="s.phone"><el-icon><Phone /></el-icon>{{ s.phone }}</span><span v-if="!s.email&&!s.phone">No contact details added</span></div></article><div v-if="!supplierList.length" class="surface-card category-empty"><el-icon><Van /></el-icon><b>No suppliers added</b><span>Connect a supplier to products from the catalogue.</span></div></div></section>
    <section v-else-if="section==='team'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">ACCESS & RESPONSIBILITY</span><h1>Team access</h1><p>Give each person the access their role needs.</p></div><el-button type="primary" @click="Object.assign(userForm,{username:'',displayName:'',password:'',role:'CLERK'});userDialog=true"><el-icon><Plus /></el-icon>Add team member</el-button></div><div class="role-cards"><article class="surface-card role-card"><span class="role-symbol role-admin"><el-icon><Key /></el-icon></span><b>Administrator</b><span>Full control of accounts, catalogue, settings and inventory.</span></article><article class="surface-card role-card"><span class="role-symbol role-manager"><el-icon><DataBoard /></el-icon></span><b>Store manager</b><span>View reports and warnings, review stock health and set priorities.</span></article><article class="surface-card role-card"><span class="role-symbol role-clerk"><el-icon><Goods /></el-icon></span><b>Stock clerk</b><span>Record stock received, dispatches, adjustments and counts.</span></article></div><div class="surface-card table-surface"><div class="table-toolbar"><span class="history-intro"><b>Store team</b><small>Access changes take effect on the next request.</small></span><span class="result-count">{{ userList.length }} members</span></div><el-table :data="userList" stripe><el-table-column label="TEAM MEMBER" min-width="280"><template #default="{row}"><span class="actor-cell"><i class="member-avatar">{{ row.displayName.split(' ').map((x:string)=>x[0]).slice(0,2).join('') }}</i><span class="member-details"><b>{{ row.displayName }}</b><small>@{{ row.username }}</small></span></span></template></el-table-column><el-table-column label="ROLE" width="210"><template #default="{row}"><el-select v-if="row.id!==auth.user?.id" :model-value="row.role" size="small" @change="changeRole(row,$event)"><el-option label="Administrator" value="ADMIN"/><el-option label="Store manager" value="MANAGER"/><el-option label="Stock clerk" value="CLERK"/></el-select><span v-else class="role-pill" :class="`role-${row.role.toLowerCase()}`">{{ roleLabel(row.role) }}</span></template></el-table-column><el-table-column label="ACCOUNT" width="180"><template #default="{row}"><span class="status-pill" :class="row.enabled?'status-good':'status-muted'"><i></i>{{ row.enabled?'Active':'Paused' }}</span></template></el-table-column><el-table-column label="ADDED" width="160"><template #default="{row}"><span class="date-cell">{{ timeFormat(row.createdAt) }}</span></template></el-table-column><el-table-column label="" width="140" align="right"><template #default="{row}"><el-button v-if="row.id!==auth.user?.id" size="small" @click="toggleUser(row)">{{ row.enabled?'Pause access':'Restore access' }}</el-button></template></el-table-column></el-table></div><div class="table-note"><el-icon><Lock /></el-icon>Permissions are checked on the server for every request, not only in the navigation.</div></section>
    <section v-else-if="section==='settings'" class="view table-view"><div class="page-heading"><div><span class="eyebrow">WORKSPACE PREFERENCES</span><h1>Store settings</h1><p>Personalise the details used throughout the workspace.</p></div></div><article class="surface-card settings-panel"><div class="settings-section-head"><span class="settings-section-icon"><el-icon><Shop /></el-icon></span><span><b>Store profile</b><small>These details help your reports feel like your store.</small></span></div><div class="settings-form"><el-form label-position="top"><el-form-item label="Store name"><el-input v-model="businessForm.businessName" maxlength="120" /></el-form-item><el-form-item label="Display currency"><el-select v-model="businessForm.currency"><el-option label="US Dollar · USD" value="USD"/><el-option label="Euro · EUR" value="EUR"/><el-option label="Pound Sterling · GBP" value="GBP"/><el-option label="Chinese Yuan · CNY" value="CNY"/><el-option label="Australian Dollar · AUD" value="AUD"/></el-select><span class="field-help">Changes the display symbol only. No exchange-rate conversion is performed.</span></el-form-item></el-form></div><div class="settings-actions"><span>Changes apply across reports and the dashboard.</span><el-button type="primary" @click="saveSettings">Save changes</el-button></div></article></section>
    <div class="global-footer"><span>Made for the rhythm of independent retail</span><span>Shelfwise <i>·</i> {{ new Date().getFullYear() }}</span></div>
   </div>
  </main>
  <el-dialog v-model="productDialog" :title="thresholdOnly?'Edit stock thresholds':productForm.id?'Edit product':'Add a product'" width="600px" destroy-on-close><el-form label-position="top" class="dialog-form"><div class="form-grid"><el-form-item label="Product name" class="span-two"><el-input v-model="productForm.name" :disabled="thresholdOnly" maxlength="180" placeholder="e.g. Whole milk 1L"/></el-form-item><el-form-item label="SKU"><el-input v-model="productForm.sku" :disabled="thresholdOnly" maxlength="64" placeholder="e.g. DAIRY-001"/></el-form-item><el-form-item label="Barcode"><el-input v-model="productForm.barcode" :disabled="thresholdOnly" maxlength="64" placeholder="Optional"/></el-form-item><el-form-item label="Category"><el-select v-model="productForm.categoryId" :disabled="thresholdOnly" clearable placeholder="Choose a category"><el-option v-for="c in categoryList" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="Supplier"><el-select v-model="productForm.supplierId" :disabled="thresholdOnly" clearable placeholder="Optional"><el-option v-for="s in supplierList" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="Unit"><el-input v-model="productForm.unit" :disabled="thresholdOnly" maxlength="40" placeholder="pcs, box, kg"/></el-form-item><el-form-item label="Unit price"><el-input-number v-model="productForm.price" :disabled="thresholdOnly" :min="0" :precision="2" :step="0.5"/></el-form-item><el-form-item label="Safety stock"><el-input-number v-model="productForm.safetyStock" :min="0" :precision="0"/></el-form-item><el-form-item label="Reorder threshold"><el-input-number v-model="productForm.reorderThreshold" :min="0" :precision="0"/></el-form-item></div><div class="form-hint"><el-icon><InfoFilled /></el-icon>Current stock changes only through a recorded transaction.</div></el-form><template #footer><el-button @click="productDialog=false">Cancel</el-button><el-button type="primary" @click="saveProduct">{{ productForm.id?'Save changes':'Add product' }}</el-button></template></el-dialog>
  <el-dialog v-model="movementDialog" title="Record stock activity" width="540px" destroy-on-close><el-form label-position="top" class="dialog-form"><el-form-item label="Product"><el-select v-model="movementForm.productId" filterable placeholder="Search your catalogue"><el-option v-for="p in productPage?.items||[]" :key="p.id" :label="`${p.name} · ${p.sku} (${p.quantity} ${p.unit})`" :value="p.id"/></el-select></el-form-item><el-form-item label="Activity type"><el-select v-model="movementForm.type"><el-option label="Receive stock" value="STOCK_IN"/><el-option label="Dispatch stock" value="STOCK_OUT"/><el-option label="Adjust quantity" value="ADJUSTMENT"/><el-option label="Record stock count" value="STOCKTAKE"/></el-select></el-form-item><el-form-item :label="movementForm.type==='STOCKTAKE'?'Counted quantity':movementForm.type==='ADJUSTMENT'?'Quantity change (+ or −)':'Quantity'"><el-input-number v-model="movementForm.quantity" :min="movementForm.type==='ADJUSTMENT'?-1000000000:movementForm.type==='STOCKTAKE'?0:1" :max="1000000000" :precision="0" controls-position="right"/></el-form-item><template v-if="movementForm.type==='STOCK_IN'"><el-form-item label="Batch number"><el-input v-model="movementForm.batchNumber" maxlength="80" placeholder="Auto-generated if empty"/></el-form-item><div class="form-grid"><el-form-item label="Production date"><el-date-picker v-model="movementForm.productionDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Expiry date"><el-date-picker v-model="movementForm.expiryDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></div></template><el-form-item label="Reason for this activity"><el-input v-model="movementForm.reason" type="textarea" maxlength="300" show-word-limit :rows="3" placeholder="e.g. Morning delivery, damaged items, weekly count"/></el-form-item><div class="form-hint"><el-icon><Lock /></el-icon>This entry records your name, the time and the before-and-after quantities.</div></el-form><template #footer><el-button @click="movementDialog=false">Cancel</el-button><el-button type="primary" :loading="saving" :disabled="saving" @click="saveMovement">Record activity</el-button></template></el-dialog>
  <el-dialog v-model="userDialog" title="Add team member" width="500px" destroy-on-close><el-form label-position="top" class="dialog-form"><el-form-item label="Full name"><el-input v-model="userForm.displayName" maxlength="100"/></el-form-item><el-form-item label="Username"><el-input v-model="userForm.username" maxlength="80" autocomplete="off"/></el-form-item><el-form-item label="Temporary password"><el-input v-model="userForm.password" type="password" show-password autocomplete="new-password"/><span class="field-help">Use at least 12 characters. Arrange a secure handover with the team member.</span></el-form-item><el-form-item label="Access role"><el-select v-model="userForm.role"><el-option label="Administrator" value="ADMIN"/><el-option label="Store manager" value="MANAGER"/><el-option label="Stock clerk" value="CLERK"/></el-select></el-form-item></el-form><template #footer><el-button @click="userDialog=false">Cancel</el-button><el-button type="primary" @click="saveUser">Create account</el-button></template></el-dialog>
  <el-dialog v-model="categoryDialog" title="Add a category" width="470px"><el-form label-position="top"><el-form-item label="Category name"><el-input v-model="categoryForm.name" maxlength="100" placeholder="e.g. Frozen goods"/></el-form-item><el-form-item label="Description"><el-input v-model="categoryForm.description" type="textarea" maxlength="500" placeholder="What belongs in this category?"/></el-form-item></el-form><template #footer><el-button @click="categoryDialog=false">Cancel</el-button><el-button type="primary" @click="saveCategory">Add category</el-button></template></el-dialog>
  <el-dialog v-model="supplierDialog" title="Add a supplier" width="500px"><el-form label-position="top"><el-form-item label="Supplier name"><el-input v-model="supplierForm.name" maxlength="120"/></el-form-item><el-form-item label="Contact person"><el-input v-model="supplierForm.contactName" maxlength="120"/></el-form-item><div class="form-grid"><el-form-item label="Email"><el-input v-model="supplierForm.email" type="email" maxlength="120"/></el-form-item><el-form-item label="Phone"><el-input v-model="supplierForm.phone" maxlength="40"/></el-form-item></div></el-form><template #footer><el-button @click="supplierDialog=false">Cancel</el-button><el-button type="primary" @click="saveSupplier">Save supplier</el-button></template></el-dialog>
 </div>
</template>
